=== lorik759/leiDina/src/main/resource/vapplication-definitons.xsd
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.vaplication.com/definition"
    xmlns:vad="http://www.vaplication.com/definition" elementFormDefault="qualified">
    <element name="Definition" type="vad:definitionType"/>

    <complexType name="definitionType">
        <sequence>
            <element name="package" maxOccurs="unbounded" minOccurs="0" type="string"/>
            <element name="beans" type="vad:beansType" minOccurs="0" maxOccurs="1"/>
        </sequence>
    </complexType>


    <complexType name="beansType">
        <sequence>
            <element name="bean" maxOccurs="unbounded" type="vad:beanDefinitionType"/>
        </sequence>
    </complexType>

    <complexType name="beanDefinitionType">
        <sequence>
            <element name="property" minOccurs="0" maxOccurs="unbounded" type="vad:propertyType"/>
        </sequence>
        <attribute name="id" type="string" use="required"/>
        <attribute name="class" type="string" use="required"/>
        <attribute name="parent" type="string"/>
    </complexType>

    <complexType name="propertyType">
        <sequence>
            <group ref="vad:propertyElements"/>
        </sequence>
        <attribute name="propertyName" type="string" use="required"/>
    </complexType>

    <group name="propertyElements">
        <choice>
            <element name="beanProperty" type="vad:beanType"/>
            <element name="listProperty" type="vad:listType"/>
            <element name="mapProperty" type="vad:mapType"/>
        </choice>
    </group>

    <complexType name="beanType">
        <attribute name="ref" type="string"/>
    </complexType>

    <complexType name="listType">
        <sequence>
            <element name="value" type="string" minOccurs="1" maxOccurs="unbounded"/>
        </sequence>
    </complexType>

    <complexType name="mapType">
        <sequence maxOccurs="unbounded" minOccurs="1">
            <element name="entry" type="vad:keyType"/>
        </sequence>
        <attribute name="keyType" type="vad:mapPropertyValues" use="required"/>
    </complexType>

    <complexType name="keyType">
        <sequence>
            <group ref="vad:propertyElements" maxOccurs="1"/>
        </sequence>
        <attribute name="key" type="string" use="required"/>
    </complexType>
    <simpleType name="mapPropertyValues">
        <restriction base="string">
            <enumeration value="class"/>
            <enumeration value="string"/>
        </restriction>
    </simpleType>
</schema>

=== lorik759/leiDina/src/test/resource/test-second-definiton.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<vad:Definition xmlns:vad="http://www.vaplication.com/definition" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.vaplication.com/definition vapplication-definitons.xsd ">
    <vad:beans>
        <vad:bean id="seconBasicBeanTest" class="main.java.leiDina.tec.persister.Entity"/>

        <vad:bean id="secondBeanRefTest" class="main.java.leiDina.tec.persister.EntityOne">
            <vad:property propertyName="beanProperty">
                <vad:mapProperty keyType="class">
                    <vad:entry key="main.java.leiDina.tec.persister.EntityOne">
                        <vad:beanProperty ref="test"/>
                    </vad:entry>
                    <vad:entry key="main.java.leiDina.tec.persister.EntityOne">
                        <vad:beanProperty ref="teste"/>
                    </vad:entry>
                </vad:mapProperty>
            </vad:property>
        </vad:bean>
    </vad:beans>
</vad:Definition>

=== lorik759/leiDina/src/main/resource/fx-service-definiton.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<vad:Definition xmlns:vad="http://www.vaplication.com/definition" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.vaplication.com/definition vapplication-definitons.xsd ">
    <vad:beans>
        <vad:bean id="genericControllerBuilder" class="main.java.leiDina.tec.javafx.factory.builder.GenericControllerBuilder"/>

        <vad:bean id="controllerFactory" class="main.java.leiDina.tec.javafx.factory.ControllerFactoryImpl">
            <vad:property propertyName="buiders">
                <vad:mapProperty keyType="class">
                    <vad:entry key="java.lang.Object">
                        <vad:beanProperty ref="genericControllerBuilder"/>
                    </vad:entry>
                </vad:mapProperty>
            </vad:property>
        </vad:bean>

        <vad:bean id="textInputNodeAssociation" class="main.java.leiDina.tec.javafx.service.TextInputNodeAssociation"/>
        <vad:bean id="numberInputNodeAssociation" class="main.java.leiDina.tec.javafx.service.NumberInputNodeAssociation"/>

        <vad:bean id="modelSceneWire" class="main.java.leiDina.tec.javafx.service.ModelSceneWire">
            <vad:property propertyName="associationMap">
                <vad:mapProperty keyType="class">
                    <vad:entry key="main.java.leiDina.tec.javafx.annotation.TextInput">
                        <vad:beanProperty ref="textInputNodeAssociation"/>
                    </vad:entry>
                    <vad:entry key="main.java.leiDina.tec.javafx.annotation.NumberInput">
                        <vad:beanProperty ref="numberInputNodeAssociation"/>
                    </vad:entry>
                </vad:mapProperty>
            </vad:property>
        </vad:bean>
    </vad:beans>
</vad:Definition>
